include:
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - kaniko-ci.yml
    ref: main

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  DOCKERFILE: Dockerfile
  REGISTRY_URL: "${IMAGE_REPOSITORY}"

stages:
  - read-secret  
  - build

# Lecture des secrets CI du build
read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

before_script: 
 - echo "REGISTRY_URL = $REGISTRY_URL"

build:
  variables:
    WORKING_DIR: "."
    EXTRA_BUILD_ARGS: --force
    IMAGE_NAME: "test-mrq"
  stage: build
  extends:
    - .kaniko:simple-build-push
