include:
  - project: "cloud-pi-native/gitlab-ci-catalog"
    ref: main
    file: "kaniko-ci.yml"

variables:
  # Utilisé comme tag d'image : "main", "feature-x", etc.
  TAG: "${CI_COMMIT_REF_SLUG}"
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:${TAG}"
  DOCKERFILE: Dockerfile
  REGISTRY_URL: "$CI_REGISTRY"

stages:
  - build

docker-build:
  stage: build
  extends:
    - .kaniko:build-push
  variables:
    WORKING_DIR: "."  # Chemin où se trouve ton Dockerfile (à la racine du dépôt app)
