include:
  - local: '.gitlab/kaniko-templates.yml'

stages:
  - build

build-image:
  stage: build
  extends: .kaniko:build-push
  variables:
    IMAGE_NAMES: my-app:$CI_COMMIT_SHORT_SHA
    IMAGE_REPOSITORY: gcr.io/ton-projet-gcp
    EXTRA_BUILD_ARGS: "--build-arg SOME_VAR=somevalue"
  only:
    - main

