include:
  - project: $CATALOG_PATH
    file:
      - kaniko-ci.yml
    ref: main

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  DOCKERFILE: Dockerfile
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:$TAG"
  REGISTRY_URL: "$CI_REGISTRY"

stages:
  - docker-build

docker-build:
  stage: docker-build
  extends:
    - .kaniko:build-push
  variables:
    WORKING_DIR: "."
