default:
  script: []

stages:
  - build

build-image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - mkdir -p /kaniko/.docker
    - echo "$DOCKER_AUTH" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination gcr.io/ton-projet-gcp/my-app:$CI_COMMIT_SHORT_SHA
      --single-snapshot
  only:
    - main
