variables:
  DOCKER_BUILDKIT: 1

.base:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - apk add --no-cache curl
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="latest"
      else
        tag="$CI_COMMIT_REF_SLUG"
      fi

stages:
  - build

build:
  extends: .base
  stage: build
  script:
    - docker build --platform linux/amd64 -t "$CI_REGISTRY_IMAGE:$tag" .
    - docker push "$CI_REGISTRY_IMAGE:$tag"
