default:
  image: alpine:latest

stages:
  - build

docker-build:
  stage: build
  image: registry.gitlab.com/gitlab-org/cluster-integration/kaniko-project/executor:debug
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${DOCKERFILE}" --destination "${IMAGE_NAME}"
  only:
    - main

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:${TAG}"
  DOCKERFILE: Dockerfile
  REGISTRY_URL: "$CI_REGISTRY"
